language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before-install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --ignore-platform-reqs

script:
  - composer check
  - composer test

env: 
  CODECOV_TOKEN='c3728a70-a0d6-406e-bffd-a5632e15b9a4'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: dev@livecommerce.com.br